name: client_app
description: Client mobile app for ordering in the restaurant system.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.0.0

  # Firebase
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0

  # Paquete compartido
  shared_logic:
    path: ../shared_logic

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true